### ISSUE TITLE
get_subreddit_gallery raising 404

### ISSUE THREAD

**Issue by SnowdogU77** [Damgaard/PyImgur#13]
This snippet of code:
picgallery = im.get_subreddit_gallery("pics")
is raising this error:
requests.exceptions.HTTPError: 404 Client Error: Not Found

I'm following the documentation perfectly, so I'm puzzled as to why this isn't working.

**Comment by Damgaard** [comment]
Package has been fixed for `get_subreddit_gallery` with v0.5.3. Upgrade your version and it should work fine.
