### ISSUE TITLE
File "C:\Python34\lib\site-packages\pyimgur\__init__.py", line 34, in <module>     from urlparse import urlparse ImportError: No module named 'urlparse'

### ISSUE THREAD

**Issue by Jarmahent** [Damgaard/PyImgur#26]

**Comment by Jarmahent** [comment]
Line 34 

    33 from base64 import b64encode
    34 from urllib import urlparse
    35 import os.path
    36 import re
    37 import sys

**CHANGE TO**

    33 from base64 import b64encode
    34 import urllib.parse
    35 import os.path
    36 import re
    37 import sys

**Comment by scavault** [comment]
Code above fixes the issue. Just replaced all instances of urlparse with urllib.parse in the __init__ file.

**Comment by moneroexamples** [comment]
you can fix that by edditing pyimmgur/__init__.py as follows

```
#from urlparse import urlparse 
from urllib import parse as urlpasre
```

**Comment by jabbalaci** [comment]
If you download the ZIPped source, it is corrected. If you install it via pip, you get the old version that doesn't work with Python 3.

Solution: the project maintainer should upload the new version to PyPI.

**Comment by Damgaard** [comment]
PyImgur 0.6.0 has now (finally) been released, which includes python3x support. This problems should now be fixed.
