### ISSUE TITLE
How do I get a user's notification?

### ISSUE THREAD

**Issue by 8bitgentleman** [Damgaard/PyImgur#33]
I got client_id, client_secret, access_token, and refresh_token just fine. Other user functions like user.name or user.get_comments() etc work fine but when I call user.get_notifications() it throws this error 
` File "/Library/Python/2.7/site-packages/pyimgur/__init__.py", line 1353, in get_notifications
    com_dict in resp['replies']]
UnboundLocalError: local variable 'msg_dict' referenced before assignment`

**Comment by Damgaard** [comment]
There was a bug in the source code. It has been fixed and a new version rolled out. To get the users notifications upgrade your version of `pyimgur` and then use your existing code. It should work without any problems now.

```bash

    pip install pyimgur --upgrade
```
