### ISSUE TITLE
Fetching title and link based on ID.

### ISSUE THREAD

**Issue by ToJa92** [Damgaard/PyImgur#7]
Hello, I'm currently writing a little script that will pull imgur links from a IRC channel and store them in a database. I would also like to print the title to the channel.

Problem is, imgur's IDs are pretty ambiguous. An ID can represent several things: a image, an album, a gallery, a picture in a gallery or even a gallery album. It seems like you can go to imgur.com/[id here] and it will happily show you whatever thing that exists on that ID, whether it's an album, a image and so on.

So, apart from doing multiple try/except blocks to get the title and link (which are the only things I'm interested in), are there any nice ways of doing this with PyImgur? It would be terrific if I could just do one request that would get all the things that IDs may have in common, where title and link is from what I gather among those.

**Comment by Damgaard** [comment]
Hi, since I haven't heard anything from you. I assume everything is working perfectly and I'm closing the issue. If you do find any missing edge cases, we'll reopen the issue and reexamine them.
